tap "cloudflare/cloudflare"
tap "fermyon/tap"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/services"
brew "asdf"
brew "gettext"
brew "glib"
brew "libx11"
brew "cloc"
brew "cloudflared"
brew "coreutils"
brew "difftastic"
brew "unbound"
brew "gnutls"
brew "icu4c@76"
brew "ffmpeg"
brew "fish"
brew "gh"
brew "git-quick-stats"
brew "gum"
brew "jq"
brew "libxfixes"
brew "libxi"
brew "mas"
brew "nginx"
brew "podman"
brew "podman-compose"
brew "python@3.10"
brew "python@3.11"
brew "qemu"
brew "rcm"
brew "redis", restart_service: :changed
brew "socket_vmnet"
brew "spoof-mac"
brew "sshuttle"
brew "starship"
brew "thefuck"
brew "tor"
brew "wimlib"
brew "yt-dlp"
cask "audacity"
cask "azure-data-studio"
cask "bunch"
cask "calibre"
cask "chromium"
cask "cheatsheet"
cask "cloudflare-warp"
cask "digikam"
cask "finicky"
cask "firefox"
cask "firefox@developer-edition"
cask "fmail2"
cask "font-caskaydia-cove-nerd-font"
cask "hammerspoon"
cask "ipfs"
cask "joplin"
cask "karabiner-elements"
cask "lasso"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-remote-desktop"
cask "monitorcontrol"
cask "multitouch"
cask "nightfall"
cask "onedrive"
cask "podman-desktop"
cask "powershell"
cask "rewind"
cask "stats"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "xamarin-mac"
mas "Developer", id: 640199958
mas "Hand Mirror", id: 1502839586
mas "Instapaper", id: 288545208
mas "Instapaper Save", id: 1481302432
mas "Kindle Classic", id: 405399194
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "OneDrive", id: 823766827
mas "Tailscale", id: 1475387142
mas "Windows App", id: 1295203466
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
