// Generated by Finicky Kickstart 
// Save as ~/.finicky.js
// Docs: https://github.com/johnste/finicky/wiki/Configuration
export default {
    defaultBrowser: "Browserosaurus",      
    // defaultBrowser: "Microsoft Edge",      
    handlers: [
      {
        // Open all Google Meet links in Google Chrome
        match: url => url.host === "meet.google.com",
        browser: "Google Meet"
      },
      {
        // Open Google Meet links from specific openers in Google Chrome
        match: (url, opener) => url.host === "meet.google.com" && ["Gmail","Google Calendar","Google Meet","Slack","Limitless"].includes(opener?.name),
        browser: "Google Meet"
      },
      {
        match: url => url.host === "localhost",
        browser: "Firefox Developer Edition"
      },
      {
        match: (url, opener) => ["Gmail","Google Calendar","Google Meet","ClockShark - Slack","Limitless"].includes(opener?.name),
        browser: {
          name: "Microsoft Edge",
          profile: "Profile 1"
        }
      },
      {
        match: (url, opener) => ["FMail2", "Messages", "OneDrive"].includes(opener?.name),
        browser: {
          name: "Firefox",
        }
      }
    ]
  }