// Generated by Finicky Kickstart 
// Save as ~/.finicky.js
// Docs: https://github.com/johnste/finicky/wiki/Configuration
module.exports = {
    defaultBrowser: "Firefox",      
    // defaultBrowser: "Microsoft Edge",      
    handlers: [
      {
        // match: /^https?:\/\/meet\.google\.com.*$/,
        match: ({url, urlString}) =>{
          finicky.log(url.host);
          return url.host === "meet.google.com";
        }
        ,browser: "Google Meet"
      },
      {
        // match: /^https?:\/\/meet\.google\.com.*$/,
        match: ({url, opener}) =>{
          ["Gmail","Google Calendar","Google Meet","Slack","Limitless"].includes(opener.name)
          finicky.log(url.host);
          return url.host === "meet.google.com" && ["Gmail","Google Calendar","Google Meet","Slack","Limitless"].includes(opener.name);
        }
        ,browser: "Google Meet"
      },
      {
        match: /^https?:\/\/localhost.*$/,
        browser: "Firefox Developer Edition"
      },
      {
        match: ({opener}) => ["Gmail","Google Calendar","Google Meet","Slack","Limitless"].includes(opener.name),
        browser: {
          name: "Microsoft Edge",
          profile: "Profile 1"
        }
      },
      {
        match: ({opener}) => ["FMail2", "Messages", "OneDrive"].includes(opener.name),
        browser: {
          name: "Firefox",
        }
        // browser: {
        //   name: "Microsoft Edge",
        //   profile: "Default"
        // }
      // },
      // { //edge is being real dumb w/ msft sites
      //   match: /^https?:\/\/.*\.microsoft\.com\/.*$/,
      //   browser: "Firefox Developer Edition"
      }
    ]
  }