// Generated by Finicky Kickstart 
// Save as ~/.finicky.js
// Docs: https://github.com/johnste/finicky/wiki/Configuration
module.exports = {
    defaultBrowser: "Microsoft Edge",      
    handlers: [
      {
        match: /^https?:\/\/meet\.google\.com\/.*$/,
        browser: "Google Meet"
      },
      {
        match: /^https?:\/\/localhost.*$/,
        browser: "Firefox Developer Edition"
      },
      {
        match: ({opener}) => ["Gmail","Google Calendar","Google Meet","Slack"].includes(opener.name),
        browser: {
          name: "Microsoft Edge",
          profile: "Profile 1"
        }
      },
      {
        match: ({opener}) => ["FMail2", "Messages", "OneDrive"].includes(opener.name),
        browser: {
          name: "Microsoft Edge",
          profile: "Default"
        }
      },
      { //edge is being real dumb w/ msft sites
        match: /^https?:\/\/.*\.microsoft\.com\/.*$/,
        browser: "Firefox Developer Edition"
      }
    ]
  }